/**
 * Bake the images in assets/ into a TypeScript module.
 *
 * The Worker has no filesystem and this project has no static-asset bucket, so
 * the two images the site serves are carried in the bundle as base64. That is
 * the whole reason this script exists: it is the only way an image can be part
 * of a single-artifact deploy.
 *
 * Run after changing anything in assets/:
 *   npm run assets:embed
 *
 * The generated file is committed. A build step that has to run before a deploy
 * is a build step someone will forget at 2am.
 */

import { createHash } from "node:crypto";
import { readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(fileURLToPath(new URL(".", import.meta.url).href), "..");
const OUT = join(ROOT, "src/assets/images.ts");

/** Served at 2x its rendered size; the icon is the favicon. */
const IMAGES = [
  { name: "PORTRAIT", file: "assets/portrait.png" },
  { name: "ICON", file: "assets/icon.png" },
] as const;

const parts: string[] = [];

for (const img of IMAGES) {
  // Read as base64 rather than as bytes: the Worker types in scope here make
  // Buffer.toString(encoding) unavailable, and base64 is the shape we want.
  const path = join(ROOT, img.file);
  const b64 = readFileSync(path, "base64");
  const size = statSync(path).size;
  const hash = createHash("sha256").update(b64, "base64").digest("hex").slice(0, 16);
  parts.push(
    `/** ${img.file} — ${size} bytes. */\n` +
      `export const ${img.name}_PNG = {\n` +
      `  etag: '"${hash}"',\n` +
      `  bytes: ${size},\n` +
      `  b64:\n    "${b64}",\n` +
      `};`,
  );
  process.stdout.write(`${img.file}: ${size} bytes -> ${b64.length} base64\n`);
}

const header = `// Generated by scripts/embed-images.ts. Do not edit by hand.
//
// The Worker has no filesystem, so the images the site serves live here as
// base64 and are decoded once per isolate. Regenerate with: npm run assets:embed

`;

writeFileSync(OUT, header + parts.join("\n\n") + "\n");
process.stdout.write(`wrote ${OUT}\n`);
